### ISSUE TITLE
Is it possible to spawn an actor in another thread?

### ISSUE THREAD

**Issue by fMeow** [Restioson/xtra#17]
In actix, an actor can be spawn in another thread by [start_in_arbiter](https://docs.rs/actix/0.10.0-alpha.3/actix/prelude/trait.Actor.html#method.start_in_arbiter) method. I wonder if it is supported in xtra too.

Currently, I fail to find a equivalent method in `xtra`. Maybe I can achieve this feature by creating an actor in another thread and spawn it, and use a `OneShot` channel to return the address to main thread?

With this feature, CPU intensive actors can be spawned in a new OS thread to boost performance.

**Comment by Restioson** [comment]
Currently, xtra has two ways of spawning actors:

1. The basic method [`Actor::create`](https://docs.rs/xtra/0.4.2/xtra/trait.Actor.html#method.create). This simply creates the actor in a ready-to-spawn state, returning a tuple of its address and its `ActorManager`, the latter of which can be used to spawn it however you please. 
2. The convenience method [`Actor::spawn`](https://docs.rs/xtra/0.4.2/xtra/trait.Actor.html#method.spawn). This creates the actor *and* spawns it onto whichever runtime is specified with the feature flags (e.g for tokio it will call `tokio::spawn(manager.manage())`).

The second method, `spawn`, is probably the most common way of spawning actors, but does **not** provide any special guarantees about where the actor will be spawned. This decision is left up to the executor, and will spawn it wherever it so chooses. I would wager that it's a fairly safe bet that a reasonably-well optimised executor would do a good job on this, but YMMV. However, as you say, most executors also do not like synchronous code to be executed on the main runtime.

The first method, `create`, gives you **full control** over where you want to spawn the actor. You are free to do whatever you want with it, as it is pretty much just a wrapper for a future waiting to be started. In fact, `spawn` simply wraps `create`. It is definitely possible to spawn the actor anywhere you wish with the `Actor::create` method. For instance, you could call the method and then call `tokio::spawn_blocking` on it or do something else with it.

NB: Actix has its own arbiter system for running actors, whereas xtra can use any system. Therefore, it is more flexible, but your solution to this problem is probably going to be more dependent on which executor you are using.

Alternatively, if you need to execute a portion of synchronous, CPU-intensive code, it might be worth spawning that onto a blocking threadpool and then `await`ing the result of that inside of the actor handler. That way, you only need to use a synchronous-task threadpool when necessary. I'm not sure how this would interact with borrowing if you need to borrow from self though, since AFAIK there is no concept of a "scoped future".

**Comment by fMeow** [comment]
Wow, thanks you so much. It really make sense. I think that `Actor::create` and `tokio::spawn_blocking` are what I am looking for.

In short, the best solution is to use `Actor::create` to get a address and a manager, and find a suitable method in async runtime to spawn the manager. 

Thank you again!

**Comment by Restioson** [comment]
By the way, it appears that tokio::spawn_blocking spawns a normal function. I confused it with Task::blocking from smol. In any case, for tokio the best solution would probably to spawn the handlers onto a blocking threadpool where needed and then await the result.

**Comment by fMeow** [comment]
That's fine. I can use `tokio::spawn` in `tokio::spawn_blocking` to spawn a manager. And in `async-std`, the `tokio::spawn_blocking` equivalent also accepts a Fn, I have tried `async_std::spawn_blocking(move || {async_std::spawn(mgr.manage())})` with `async-std` and it works like a charm.

**Comment by Restioson** [comment]
As far as I'm aware, that simply spawns the spawn function onto a thread. I.e, it is still running on the non blocking executor.

**Comment by fMeow** [comment]
At least for `async_std`, the thread id given by `std::thread::current().id()` is different.

But wait, using `async_std`, even `Actor::spawn` can spawn the actor in a thread with different thread id.

That's wierd. You are right, it all depends on the future runtime.

**Comment by Restioson** [comment]
Yeah. If you just want to run them on different threads, use spawn, or leave it up to the executor. If you want to run sections of blocking code (file IO, hashing, etc), I'd use spawn blocking and then .await the task in the handler.
