### ISSUE TITLE
Import `xtra-addons` functionality

### ISSUE THREAD

**Issue by mneumann** [Restioson/xtra#31]
If you feel that this is useful to xtra, feel free to import the `Registry` and `Broker` functionality from `xtra-addons` crate into `xtra`. The work is based on what currently exists in xactor and brings xtra feature-wise en par with xactor. Xtra's feature set is even greater as it allows for actors sharing the same message queu (work stealing) which xactor currently lacks, and also xactor does not have the notification system that xtra has (but is generally faster).

**Comment by Restioson** [comment]
I've taken a look at `xtra-addons`, and the functionality definitely looks useful! 

- The registry I'd rather leave to an external crate since I'm not sure how common of a usecase this would be. However, having it an addons crate rather than reimplementing it each time is good, and thank you for that!
- I'm not entirely sure on what Broker does. How does the publish and subscribe work exactly?

Maybe it could be mentioned in the readme, since it seems useful!

**Comment by mneumann** [comment]
@Restioson The `Broker` is just doing "pubsub". Together with the `Registry` it's very easy to use:

```rust
let subscription1 = Broker::<MessageA>::from_registry().await.subscribe(myactor).await?;

// somewhere else...

Broker::<MessageA>::from_registry().await.publish(MessageA { ... });
```

A `Broker<T: Message>` is an actor that `Handles` the `Subscribe`, `Unsubscribe` and `T` messages. The `Subscribe` message passes the `MessageChannel<T>` of the subscribing actor to the Broker actor and this registers it in a btree. When `T` comes in to the `Broker`  it just broadcasts it to any registered actor.

**Comment by mneumann** [comment]
@Restioson Benchmark: I am running [this very unscientific benchmark](https://gitlab.com/mneumann_ntecs/actor-ring-benchmark). Go to `Implementations/Rust/Xtra` and then run something like `cargo run --release -- 1000000 1000000`. The same for the `Xactor` implementation. It's a simple ring benchmark. 

To me personally, the performance doesn't really matter much. It's more important being able to do work-stealing.

**Comment by Restioson** [comment]
Ah alright, thanks! Might play around with using `tracing` to break down what is taking up the most time.

**Comment by Restioson** [comment]
About pub/sub functionality, I definitely think it's useful but maybe not to all projects that use xtra. I'd like to keep the base library as simple as I can, and then allow these kinds of extra crates like xtra-addons (and `spaad`, which I created myself as an addon crate :) ) to use the flexible public API to implement these features. IMO, unless it can't reasonably not be in xtra proper, then external crates are good (similar to the microkernel design principle in a way). Thank you for your work on xtra-addons though -- this is not to devalue it, I just want to keep the *main* crate simple. Since it seems useful, perhaps I could mention it in the readme so that more people can find it?

**Comment by mneumann** [comment]
I like that `xtra` being just the core and not bloated with "unused" features. Just mentioned it here because `xactor` ships with that, and hey, maybe it's useful to someone else :).

**Comment by mneumann** [comment]
@Restioson Performance: My rough guess is that it's because an Actor has to `select` on both the notification mailbox *and* the message mailbox. Also Actor creation would be slower because it has to create two mailboxes instead of just one.

**Comment by Restioson** [comment]
Yea, in xtras benchmarks we did lose some performance due to workstealing, but it was gained back by switching to flume over futures channels. Additionally the mpmc futures channel that we are using is not that optimized - I wrote it myself because there was nothing else lightweight that I could find.
