### ISSUE TITLE
Allow actors to `poll` other futures as part of their event loop?

### ISSUE THREAD

**Issue by thomaseizinger** [Restioson/xtra#41]
I am trying to integrate `xtra` with `libp2p`.

`libp2p`'s main design is a big state machine that is called a `Swarm`. I has a cancellation-safe, async `next` method but also a manual `poll_next_unpin` function that advances the internal state.

Calling this function is necessary to have the network layer (represented by the `Swarm`) make progress. Additionally, in order to interact with the `Swarm`, one needs a mutable reference.

It would be nice if `xtra` could expose a way of embedding another async component like `Swarm` that could be polled as part of its event loop. Polling the `Swarm` yields events which I'd like to handle within the actor, probably as notifications to itself?

`attach_stream` is not an option because I still need a &mut reference to the `Swarm` whenever I want to interact with the network layer.

The only way of integrating `xtra` with `libp2p` at the moment is to `Arc<Mutex>` the `Swarm`. This works but it would be nice if there were a more elegant solution!

Thoughts?

**Comment by Restioson** [comment]
Hm, as far as the event loop of the actor goes, it lives in [`Context::run`](https://github.com/Restioson/xtra/blob/master/src/context.rs#L191). The main question to resolve, I guess, would be an elegant way to integrate this loop with the other future to run. Two other possible methods of integration would be [`Context::handle_while`](https://github.com/Restioson/xtra/blob/master/src/context.rs#L320) and [`Context::yield_once`](https://github.com/Restioson/xtra/blob/master/src/context.rs#L302). I wonder if the main `Context::run` loop could be replaced by a custom `Context::handle_while` loop? Something like

```rust
let actor = MyActor;
let (addr, ctx) = Context::new(None);

loop {
    ctx.handle_while(actor, swarm.next()).await
}
```

However, if the actor needs a mutable reference to the swarm, I'm not sure how this could work in any case. It basically would mean that instead of selecting over the two futures, you would need to run one and then the other. Something like

```rust
let actor = MyActor { swarm };
let (addr, ctx) = Context::new(None);

loop {
    ctx.yield_once(actor).await;
    actor.swarm.next().await;
}
```

However, this kind of functionality might imply the need for a little bit of a refactor of `Context`. There seems to be a little bit of code duplication across everything, for reasons I don't quite remember. It also seems like `handle_while` *might* inhibit an actor behind stopped properly, so in any case it should be refactored. If it can be refactored in a flexible way, such that there is space to simply implement a custom event loop for an actor like so, that might be a very nice, elegant solution. Let me know what you think!

**Comment by thomaseizinger** [comment]
I was more thinking along the lines of extending the `Actor` trait with a custom `poll` function that by default does not do anything. This `poll` call-back could be called as part of the different event-loops within `Context`.

Alternatively, we could also add an `async fn tick` to `Actor` but I think `poll` would be more flexible.

Instead of `future::select()`, we would probably have to move towards a `select!` macro to make sure they are all polled simultaneously.

**Comment by Restioson** [comment]
> I was more thinking along the lines of extending the Actor trait with a custom poll function that by default does not do anything. This poll call-back could be called as part of the different event-loops within Context.

When would this be called?

> Instead of future::select(), we would probably have to move towards a select! macro to make sure they are all polled simultaneously.

As far as `select` goes, it's important to make sure that none of the 3 things selected over are starved (address incoming messages, broadcast messages, and custom future).

**Comment by thomaseizinger** [comment]
> > I was more thinking along the lines of extending the Actor trait with a custom poll function that by default does not do anything. This poll call-back could be called as part of the different event-loops within Context.
> 
> When would this be called?

We would have to incorporate it as part of the `select` via `future::poll_fn` or something like that.

I will see to make a PoC for this.

> > Instead of future::select(), we would probably have to move towards a select! macro to make sure they are all polled simultaneously.
> 
> As far as `select` goes, it's important to make sure that none of the 3 things selected over are starved (address incoming messages, broadcast messages, and custom future).

As long as all futures involved are cancellation-safe, I don't think there should be any issues.

**Comment by Restioson** [comment]
> I posted up a PoC here: #44

> I decided to for now create a separate run function that simply adds a Stream trait bound to the actor. That means, in case the Actor implements Stream, that Stream will be polled in addition to the addresses.

Cool, I'll take a look!

> To keep this library lean, what do you think of exposing some of the internals of the Context event loop such that library users could perhaps write their own event loop for an actor?

Yea, this is definitely a possible, elegant solution - this is what I meant [in this comment](https://github.com/Restioson/xtra/issues/41#issuecomment-934231544).

**Comment by thomaseizinger** [comment]
> so that there doesn't need to be any empty implementation of Stream for every actor.

Unless you want to use the new run2 function, there is no need for Stream impl on the actor!

We could support this usecase by having two functions on `Context`: One that has a # Stream trait-bound and one that doesn't.

> Yea, this is definitely a possible, elegant solution - this is what I meant in this comment.

Those suggestions don't poll the two futures simultaneously though. The use of select is really important in a user-provided event-loop.

To make the user-provided eventloop work, `poll` on `Context` can't take `&mut Actor`, otherwise the Stream impl can't borrow mutably. Hence I think the best low-level primitive to expose from `Context` might be a `next_msg` function that polls both receivers and returns the next message. The user would then have to do the message handling (ie passing the actor to the message) outside of `Context`.

**Comment by Restioson** [comment]
Closed by https://github.com/Restioson/xtra/pull/97!
