### ISSUE TITLE
Could `Address` implement `fmt::Debug`?

### ISSUE THREAD

**Issue by thomaseizinger** [Restioson/xtra#54]
Sometimes it is useful for messages to implement `fmt::Debug` but if they contain `Address`es, that is not possible without a manual impl. Could `Address` implement `Debug`?

Not sure if we can print something useful but the counter value could be interesting for example!

**Comment by Restioson** [comment]
The reason it is currently unimplemented is due to there not being much interesting stuff to print. I'm not sure we want to print the counter since it is somewhat of an implementation detail at the moment and could fluctuate internally. We could just make an implementation that prints `Address<{ type name of actor }>`

**Comment by thomaseizinger** [comment]
I am less interested in printing something meaningful and more coming from the perspective being able to derive `Debug` on other structs that contain `Address`es. Currently, `Address` not implementing `Debug` is a blocker for that and requires either a manual implementation or a 3rd party macro such a `derivative`.

> We could just make an implementation that prints `Address<{ type name of actor }>`

I think that is a good idea!

**Comment by Restioson** [comment]
Does something like #67 make sense?
