### ISSUE TITLE
Discussion: Smaller and safer API surface

### ISSUE THREAD

**Issue by thomaseizinger** [Restioson/xtra#71]
`xtra` wants to be a _tiny, fast, and safe actor framework_.

After working with it for a while, I think this is mostly true but I also think we can do better, mostly on the _tiny_ and _safe_ part. I'd assume there are also performance gains to be made but I know where little about that so I am going to leave that for people with more experience.

At the moment, `xtra`'s API is already fairly small which I'd consider to be a good thing. However, there are some parts that I'd consider to be inconsistent and where I think we could do better in terms of composability. Additionally, there are some feature where I am not sure whether they need to necessarily be in the core `xtra` crate.

1. `do_send`, `do_send_async`, `send`.

We have 3 APIs for sending messages on an `Address`. In our project, we [ban](https://github.com/itchysats/itchysats/blob/6ef58b2b5fbce8535c41a394e748fb45e1a9d8dd/clippy.toml#L2-L4) the `do_send` ones. We consider them to be foot-guns because they silently drop return values which could be a `Result` and thus, things might be failing without one noticing. I'd like to propose to remove those from the public API. Asynchronous sending can be achieved by spawning the `SendFuture` into an executor. The fact that our underlying channels have a dedicated _async` way of sending messages should be hidden IMO.

2. `Address::attach_stream`

A nice convenience method that we used a fair bit initially but quickly realized, that it is not as useful as it initially seems, primarily because it does not give you a way of dealing with the return value of the `Handler`. I think this function can be removed or moved into some kind of `xtra-ext` crate. It builds on top of the `Address::send` API and could thus easily live in another crate.

3. `Context::notify_interval`

We have found this function to be problematic in two ways:

a. It sends messages asynchronously to the actor, thus potentially piling up a number of messages if the actor cannot process them quickly enough.
b. It does not allow for an error handling policy. We have many handlers that are invoked on an interval that can fail (background sync jobs) but their failure should not abort the loop but instead log a message.

Given that the function really only composes `send`, I think we should try and move it out of the core `xtra` crate and provide ways for users to easily create their own "send on an interval" loop. Perhaps this can be combined with `Address::attach_stream`? An stream of intervals that maps to messages would achieve the same outcome I think.

4. `Context::notify_after`

Similar to `notify_interval` this function only composes `send` and thus, I think we could lift it into a separate crate, minimizing the API surface of `Context`.

5. `Context::{notify,notify_all}`

We haven't found a usecase for these but it is one of those feature that if not provided by the core crate, are impossible to implement on top. I might be worth debating and clearly documenting, when and what it should be used for. Given that we already have a way of sending messages to an actor, it is not a completely orthogonal feature either.

6. `AddressSink` and friends

Whilst I think interoperability with common traits in the `async` ecosystem is important, I've been wondering whether it is worth maintaining a fairly big chunk of code for this feature. Similar to `Context::notify`, there are some orthogonality concerns with `Address::send`.

cc @zesterer Curious to hear if any of this overlaps with your thoughts that you mentioned in https://github.com/Restioson/xtra/issues/68#issuecomment-1097859504.

**Comment by thomaseizinger** [comment]
> 6. `AddressSink` and friends
> 
> 
> Whilst I think interoperability with common traits in the `async` ecosystem is important, I've been wondering whether it is worth maintaining a fairly big chunk of code for this feature. Similar to `Context::notify`, there are some orthogonality concerns with `Address::send`.

If we extend `Address` to not only holder a `Sender` but also a `Sink`, could we then directly implement `Sink` for `Address` and remove the `AddressSink` struct?

**Comment by thomaseizinger** [comment]
> If we extend `Address` to not only holder a `Sender` but also a `Sink`, could we then directly implement `Sink` for `Address` and remove the `AddressSink` struct?

Turns out `SendSink` is not `Sync` and thus we would have to drop the `+ Sync` requirement on `MessageChannel`.

**Comment by zesterer** [comment]
These seem like good points! In particular, a focus on back-pressure over failure is always welcome.

**Comment by Restioson** [comment]
Thanks for this! Overall, the sending API is overdue a new look, since xtra has changed a lot from 0.1 and the API should reflect this. As it is, there is a little bit of weirdness. 


I've been reading over it and I'll just write my thoughts below as they come if that's okay:

> `do_send`, `do_send_async`, `send`.
>Asynchronous sending can be achieved by spawning the SendFuture into an executor. The fact that our underlying channels have a dedicated _async` way of sending messages should be hidden IMO.

The main issue at hand here, I think, is to do with backpressure. The difference between `do_send_async` and `do_send` is that if the mailbox is bounded and full, then `do_send_async` will allow the sender to pause and wait asynchronously for the mailbox to be emptied before its sent. By comparison, `do_send` will simply block until the mailbox is empty, which is not necessarily ideal for asynchronous usecases, since it could block an async executor thread for a long time.

> `Address::attach_stream`
> A nice convenience method that we used a fair bit initially but quickly realized, **that it is not as useful as it initially seems, primarily because it does not give you a way of dealing with the return value of the Handler**. I think this function can be removed or moved into some kind of xtra-ext crate. It builds on top of the Address::send API and could thus easily live in another crate.

I've mostly used this in cases where I want an actor to process a stream of websocket messages, having the actor hold the sending part of the stream. In this case, the return value is sent back directly by the actor itself. Like you said, it's just a convenience method and could definitely go in an extension crate. I do wonder if it could be reasonably improved to provide the return value in such a way that reduces boilerplate, though? Once you want to find the return value though, you might end up writing just about as much code to do it yourself as you would have with a helper, though. 

>  Perhaps this can be combined with Address::attach_stream? An stream of intervals that maps to messages would achieve the same outcome I think.

I think it's probably worth discussing this in a little more depth prior to merging anything in like #73 or #70. I think that a composable solution with more stuff sitting outside of xtra than inside would be the best. I'm not really sure I understand all the different use cases at play in #73 particularly, so I have held off for now on commenting much. If we can come up with a couple potential use cases maybe they can be unified in some way. If we do remove these methods, though, perhaps we could introduce examples in the docs or some kind of list of ways to achieve past features, just so that users know how to upgrade from the old APIs to the composable solution.

> `Context::notify_after`

I'm in agreement about moving this to some kind of extension crate.

PS:

- Something from my side on the sending API is that `send` is currently a bit weird. It acts more like `do_send_async` chained with a receive for the return value, as opposed to `do_send` and then a receive. What I mean by this is that `send`s must be polled to send anything at all, which seems obvious until compared to `do_send`. The only difference in naming is the `do` part, which differentiates based on return, but there is that additional difference in behaviour too in that `do_send` will send immediately whereas `send` will not.  There used to actually be a `send_async` method which was essentially today's `send`. Streamlining this in a way that makes sense is definitely needed!
- The idea of moving stuff into extension crates is nice, since it would make the API and code surface for xtra itself smaller to maintain whilst not losing too much in the way of convenience

**Comment by thomaseizinger** [comment]
> > `do_send`, `do_send_async`, `send`.
> > Asynchronous sending can be achieved by spawning the SendFuture into an executor. The fact that our underlying channels have a dedicated _async` way of sending messages should be hidden IMO.
> 
> The main issue at hand here, I think, is to do with backpressure. The difference between `do_send_async` and `do_send` is that if the mailbox is bounded and full, then `do_send_async` will allow the sender to pause and wait asynchronously for the mailbox to be emptied before its sent. By comparison, `do_send` will simply block until the mailbox is empty, which is not necessarily ideal for asynchronous usecases, since it could block an async executor thread for a long time.

That is a fair point, I did not think about back-pressure.

One of `xtra`'s main feature to me is that it is `async`-native. From that PoV, I think the `send` API should be `async` and we simply only need to agree on whether we want back-pressure or not.

I think we do want back-pressure in the form of pausing the `send` task. For `Address::send`, this is easy to do and is in fact how the implementation in https://github.com/Restioson/xtra/pull/74 behaves.
For the `MessageChannel` implementations, I think we can only do this with another allocation as we cannot name the actor type in the return value and thus would have to box up an `async` block that awaits the `SendFut` from flume.

We could make the back-pressure stuff configurable, similar as to how https://github.com/Restioson/xtra/pull/74 makes the `recv_async` part configurable: The future could fail in case the mailbox is bounded and full although I frankly don't quite know why anyone would want that.

> > `Address::attach_stream`
> > A nice convenience method that we used a fair bit initially but quickly realized, **that it is not as useful as it initially seems, primarily because it does not give you a way of dealing with the return value of the Handler**. I think this function can be removed or moved into some kind of xtra-ext crate. It builds on top of the Address::send API and could thus easily live in another crate.
> 
> I've mostly used this in cases where I want an actor to process a stream of websocket messages, having the actor hold the sending part of the stream. In this case, the return value is sent back directly by the actor itself. Like you said, it's just a convenience method and could definitely go in an extension crate. I do wonder if it could be reasonably improved to provide the return value in such a way that reduces boilerplate, though? Once you want to find the return value though, you might end up writing just about as much code to do it yourself as you would have with a helper, though.

We have used this in a similar way but the `KeepRunning` part always confused me, esp. with the lack of a supervisor that would restart the actor in case it fails. Did you see [the example](https://github.com/Restioson/xtra/blob/c973d96e85792ce6aa2e1e2b00237ef5e54c9416/examples/address_is_sink.rs) I added in https://github.com/Restioson/xtra/pull/73?

> > Perhaps this can be combined with Address::attach_stream? An stream of intervals that maps to messages would achieve the same outcome I think.
> 
> I think it's probably worth discussing this in a little more depth prior to merging anything in like #73 or #70. I think that a composable solution with more stuff sitting outside of xtra than inside would be the best. I'm not really sure I understand all the different use cases at play in #73 particularly, so I have held off for now on commenting much. If we can come up with a couple potential use cases maybe they can be unified in some way. If we do remove these methods, though, perhaps we could introduce examples in the docs or some kind of list of ways to achieve past features, just so that users know how to upgrade from the old APIs to the composable solution.

I've commented on https://github.com/Restioson/xtra/pull/73 to see if we can merge a non-controversial subset of it and discuss the deprecation of existing features at a later point.

> > `Context::notify_after`
> 
> I'm in agreement about moving this to some kind of extension crate.

Do we need to retain this function at all? I am not sure if it the usecase comes up often enough that it warrants its own method? It can be achieved by composing `.send` with an executor of your choice and a timer implementation:

```rust
tokio::spawn(async move {
	tokio::time::sleep(Duration::from_secs(10)).await;
	address.send(Foo).await;
});
```

If the user wishes to not stop the actor from being kept alive, they can downgrade the address. How to solve this requires a fair bit of knowledge but we could easily add an example that clearly explains what is at work here.

**Comment by thomaseizinger** [comment]
I had an idea on how we can do back-pressure with the `MessageChannel`s but it involves an extra allocation per message that is being sent: [`030b883` (#74)](https://github.com/Restioson/xtra/pull/74/commits/030b88306b22544346168f7a0553e76a3e052258)

Let me know what you think.

**Comment by zesterer** [comment]
From our perspective, the key reason that we're interested in `xtra` is specifically because `Handler::handle` is `async`, allowing us to correctly manage back pressure. I definitely feel that back pressure handling should be front-and-centre, with more fallible options being there as an opt-in when you need very low latency. Additionally, fully committing to having things be async-centric is likely going to result in a much better user experience than attempting to straddle the gap between the async and the sync world.

**Comment by thomaseizinger** [comment]
@zesterer If you find some free time, I'd much appreciate your input on the open PRs to see whether we are going in the right direction here.

The default with #74 would be backpressure for both, `Address::send` and `MessageChannel::send`.

**Comment by thomaseizinger** [comment]
I have a feeling the notion of "multiple actors behind one address" is also something that we might be able to compose on top of `xtra`.

If we manage to land the "context-refactor" PR, the then accessible primitives for building a custom event-loop might allow to build an `ActorPool` abstraction that introduces its own `Address` and dispatches messages in a message-stealing fashion.

This would remove a fair bit of complexity from the core crate because we wouldn't have to deal with the notion of single vs broadcast message everywhere.

**Comment by Sytten** [comment]
Hi! I am adding my small bit here.
It could be nice to allow an API for handlers that only need read only access to the actor to allow parallel processing of messages.

This is one feature that is very interesting in actix. One can access the actor state, then do some async work, then get back the actor state.

**Comment by thomaseizinger** [comment]
> Hi! I am adding my small bit here.
> It could be nice to allow an API for handlers that only need read only access to the actor to allow parallel processing of messages.
> 
> This is one feature that is very interesting in actix. One can access the actor state, then do some async work, then get back the actor state.

This is an interesting idea but I don't know if it is possible without unsafe code?

A pattern that we use a lot is:

- Read necessary actor state
- Grab an address from the Context
- Spawn a task
- Send message to actor at end of task

The initial reading is so fast that I am not sure whether it makes much of a difference to parallelise that? Would have to benchmark.

**Comment by Restioson** [comment]
> The initial reading is so fast that I am not sure whether it makes much of a difference to parallelise that? Would have to benchmark.

It should be on the order of nanoseconds or of microseconds so it is pretty fast, yea. If the async work involved does not need to refer to the actor or context, then `handle_while` (now renamed to `join`) might work?

**Comment by thomaseizinger** [comment]
This is all complete with only #123 and #125 still open. Closing as a result.
